export interface ITask {
  id: string;
  parentId: string;
  title: string;
  description: string;
  mark: string | null;
  priority: string;
  multitask: string;
  notViewed: string;
  replicate: string;
  stageId: string;
  createdBy: string;
  createdDate: string;
  responsibleId: string;
  changedBy: string;
  changedDate: string;
  statusChangedBy: string;
  closedBy: string;
  closedDate: string;
  activityDate: string;
  dateStart: string | null;
  deadline: string;
  startDatePlan: string | null;
  endDatePlan: string | null;
  guid: string;
  xmlId: string | null;
  commentsCount: string;
  serviceCommentsCount: string;
  allowChangeDeadline: string;
  allowTimeTracking: string;
  taskControl: string;
  addInReport: string;
  forkedByTemplateId: string | null;
  timeEstimate: string;
  timeSpentInLogs: string;
  matchWorkTime: string;
  forumTopicId: string;
  forumId: string;
  siteId: string;
  subordinate: string;
  exchangeModified: string | null;
  exchangeId: string | null;
  outlookVersion: string;
  viewedDate: string | null;
  sorting: string | null;
  durationFact: string;
  isMuted: string;
  isPinned: string;
  isPinnedInGroup: string;
  flowId: string | null;
  descriptionInBbcode: string;
  status: string;
  statusChangedDate: string;
  durationPlan: string;
  durationType: string;
  favorite: string;
  groupId: string;
  auditors: string[];
  accomplices: string[];
  newCommentsCount: number;
  group: {
    id: string;
    name: string;
    opened: boolean;
    membersCount: number;
    image: string;
    additionalData: any[];
  };
  creator: {
    id: string;
    name: string;
    link: string;
    icon: string;
    workPosition: string;
  };
  responsible: {
    id: string;
    name: string;
    link: string;
    icon: string;
    workPosition: string | null;
  };
  accomplicesData: any[];
  auditorsData: any[];
  subStatus: string;
}
